### ISSUE TITLE
NetApp 7mode dashboard request

### ISSUE THREAD

**Issue by jorbour** [NetApp/harvest#383]
A customer is having trouble seeing certain information on the 7mode dashboard. Below are three examples of what we would like adjusted on the dashboard and each example is accompanied by a screenshot that is in the word doc attached.

Screenshot 1:  
Left: CMODE
Right:  7MODE
 
-  "Physical Space Used" does not show on 7MODE.
-  Also, "Space Used%” calculation is questionable from us when looking at the “Total Space” and "Available Space”

Screenshot 2:
 
For the "Netapp Details Volume" dashboard, metrics only show on CMODE, not 7MODE

Screenshot 3:
If we have the same dashboard for 7mode and CMODE, how is it going to work since 7mode does not have SVM variable?  Although we tried to remove the SVM variable to test the 7mode, it is still not working.

<img width="640" alt="harvestdash1image025" src="https://user-images.githubusercontent.com/88462448/128261764-0ba6baff-02ea-4553-911c-84404dce023c.png">

**Comment by cgrinds** [comment]
hi @jorbour we're evaluating what can be done with 7-mode dashboards - see also #415

**Comment by cgrinds** [comment]
Summary of fixes in issue:
- FIXED Volume and node dashboards work with 7-mode
- FIXED `Physical Space Used` is displayed in 7-mode aggregate dashboard
- NOT FIXED `Space Used%` is missing from 7-mode aggregate dashboard - see #423 
- Agreed on SVM problem - this is an issue with unified dashboards. The best way to address this is by splitting dashboards into two distinct 7-mode and c-mode sets. We will take that up in #441

Please verify that the two issues above are fixed and we'll close this issue and take up the remaining work in #441 and #423.

**Comment by rahulguptajss** [comment]
@Hardikl  Could you check if all pending issues are now solved in main branch?

**Comment by Hardikl** [comment]
Issue 1: "Physical Space Used" does not show on 7MODE.
Fix: chart was renamed to "Space Used" as 7 mode don't have physical and logical concept. 

Issue 2: "Space Used%” calculation is questionable from us when looking at the “Total Space” and "Available Space”
Not Fixed Yet. --> It is due to this avg.  
query: avg(aggr_space_used_percent{datacenter="$Datacenter",node=~"$Node",aggr=~"$Aggregate"})

Prometheus shows this 3 values and grafana show 37.33% which is avgerage.
![image](https://user-images.githubusercontent.com/83282894/136030132-c6553a18-ec8b-4210-8465-b992957920f2.png)

Issue 3: For the "Netapp Details Volume" dashboard, metrics only show on CMODE, not 7MODE
Fix: As part of splitting dashboards, We can covered detail pages and handled available/non-available panels from details pages.

Issue 4: If we have the same dashboard for 7mode and CMODE, how is it going to work since 7mode does not have SVM variable? Although we tried to remove the SVM variable to test the 7mode, it is still not working.
Fix: 7 mode volume dashboard is working file with svm variable after splitting.

-------------------
open item: Issue 2, It is due to avg operation.
